### ISSUE TITLE
Add a "default" cache provider

### ISSUE THREAD

**Issue by aequasi** [php-cache/doctrine-adapter-bundle#7]
The first provider, or the one named default, should be the "default" provider, with a service id alias of: `cache.default` and `cache.provider.default` (if no provider named default)

**Comment by Nyholm** [comment]
By implementing this we introduce some "magic". Current implementation gives the user more control and understanding what cache they are using. 

How many cache services do you think a typical user is using?

I have two installed. One pure cache and another one that I use as a storage.

**Comment by aequasi** [comment]
Its a common feature that doctrine uses for their ORM/ODM, SncRedisBundle uses, and a few others. For DX reasons, i think its important to have, even if it is a little magic.

From discussions i've had recently, several people are only using one cache service.

Like i said though, its just an alias to the first, or default provider. The user will still have control

**Comment by Nyholm** [comment]
Okey, let's do it. Will you send a PR or should I?

**Comment by aequasi** [comment]
i can, may have to wait till after the weekend though

A. Scherer

**Comment by Nyholm** [comment]
Great!

**Comment by Nyholm** [comment]
Maybe create an alias as just `cache`?

**Comment by aequasi** [comment]
Yeah, that could work

**Comment by Nyholm** [comment]
Closed by #10
